// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

var findTheDifference = function (s, t) {
  var sarr = [];
  for (var i = 0; i < 26; i++) {
    sarr[i] = 0;
  }
  for (var i = 0; i < s.length; i++) {
    sarr[s.charCodeAt(i) - 97]++;
  }
  for (var i = 0; i < t.length; i++) {
    sarr[t.charCodeAt(i) - 97]--;
  }
  return String.fromCharCode(sarr.indexOf(-1) + 97);
};
